---
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: 6dm4vjIlWxWf1hxfrCdmoSY8yLfdjnkEid+RON1xbhA=

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: 6dm4vjIlWxWf1hxfrCdmoSY8yLfdjnkEid+RON1xbhA=

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
