---
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  SECURE_SCHEME: HTTP
  SENDGRID_API_KEY: <look up in sendgrid dashboard>
  SENDGRID_FROM_EMAIL: chiyuh@gapp.nthu.edu.tw 
  MSG_KEY: JvVdsdIw0mDQMdpHfMHDYQz7BRJEAnRx2yq476xTtgQ=
  GITHUB_ACCOUNT_URL: https://api.github.com/user

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  SECURE_SCHEME: HTTP
  SENDGRID_API_KEY: <look up in sendgrid dashboard>
  SENDGRID_FROM_EMAIL: chiyuh@gapp.nthu.edu.tw 
  MSG_KEY: JvVdsdIw0mDQMdpHfMHDYQz7BRJEAnRx2yq476xTtgQ=

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  SECURE_SCHEME: HTTPS
  SENDGRID_API_KEY: <look up in sendgrid dashboard>
  SENDGRID_FROM_EMAIL: chiyuh@gapp.nthu.edu.tw 
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
